<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Customers.aspx.cs" Inherits="Circulado_Books.admin.Customers" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title></title>
</head>
<body>
    <form id="Form1" runat="server">

        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Back To Admin Page" />
        <br />
        <br />

        <asp:TextBox ID="TextBox1" runat="server" Width="436px"></asp:TextBox>
        <asp:Button ID="Srch_Button" runat="server" OnClick="Srch_Button_Click" Text="Search" Width="113px" />
        <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" CellPadding="4" ForeColor="#333333" GridLines="None" Width="823px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="c_id">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="c_name" HeaderText="Customer Name" SortExpression="c_name" />
                <asp:BoundField DataField="Email" HeaderText="Customer Email" SortExpression="Email" />
                <asp:BoundField DataField="c_address" HeaderText="Customer Address" SortExpression="c_address" />
            </Columns>
            <EditRowStyle BackColor="#7C6F57" />
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#E3EAEB" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F8FAFA" />
            <SortedAscendingHeaderStyle BackColor="#246B61" />
            <SortedDescendingCellStyle BackColor="#D4DFE1" />
            <SortedDescendingHeaderStyle BackColor="#15524A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=(localdb)\Projects;Initial Catalog=Circulado_Database;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False"
            SelectCommand="SELECT [c_name], [Email], [c_address], [c_id] FROM [Customers] WHERE [c_name] NOT LIKE '%admin%'"
    UpdateCommand="UPDATE [Customers] SET [c_name] = @c_name, [Email] = @Email, [c_address] = @c_address WHERE [c_id] = @c_id"
    DeleteCommand="DELETE FROM [Customers] WHERE [c_id] = @c_id"
    InsertCommand="INSERT INTO [Customers] ([c_name], [Email], [c_address]) VALUES (@c_name, @Email, @c_address)">
    <DeleteParameters>
        <asp:Parameter Name="c_id" Type="Int32" />
    </DeleteParameters>
    <InsertParameters>
        <asp:Parameter Name="c_name" Type="String" />
        <asp:Parameter Name="Email" Type="String" />
        <asp:Parameter Name="c_address" Type="String" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="c_name" Type="String" />
        <asp:Parameter Name="Email" Type="String" />
        <asp:Parameter Name="c_address" Type="String" />
        <asp:Parameter Name="c_id" Type="Int32" />
    </UpdateParameters>
        </asp:SqlDataSource>
        <asp:Label ID="Label1" runat="server" Text="Name:"></asp:Label>
        <br />
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
        <br />
        Email:<br />
        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
        <br />
        Address<br />
        <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
        <br />
        <asp:Button ID="AddButton" runat="server" OnClick="AddButton_Click" Text="ADD" Width="140px" />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        <br />
    </form>
</body>
</html>
